import org.jboss.forge.roaster.Roaster;
import org.jboss.forge.roaster.model.source.*;
import org.json.JSONArray;
import org.json.JSONObject;

import java.io.*;
import java.nio.file.*;
import java.util.*;

/**
 * Enterprise Java Service Generator using Roaster
 *
 * Generates Spring @Service classes with proper validation.
 * Roaster can both GENERATE and VALIDATE Java code.
 */
public class ServiceGenerator {

    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            System.err.println("Usage: java ServiceGenerator <input_json> <output_dir>");
            System.exit(1);
        }

        String inputJsonPath = args[0];
        String outputDir = args[1];

        System.out.println("=== ServiceGenerator V3 ===");
        System.out.println("Input JSON: " + inputJsonPath);
        System.out.println("Output Dir: " + outputDir);

        // Read generation plan
        String jsonContent = new String(Files.readAllBytes(Paths.get(inputJsonPath)));
        JSONObject generationPlan = new JSONObject(jsonContent);

        // Extract services
        JSONArray services = generationPlan.getJSONArray("services");
        String packageName = generationPlan.getString("package_name");

        System.out.println("Package: " + packageName);
        System.out.println("Services to generate: " + services.length());

        // Generate each service
        for (int i = 0; i < services.length(); i++) {
            JSONObject service = services.getJSONObject(i);
            generateService(service, packageName, outputDir);
        }

        System.out.println("✓ Generated " + services.length() + " services successfully");
    }

    private static void generateService(JSONObject serviceData, String packageName, String outputDir) throws IOException {
        // Read actual fields from generation plan
        String programName = serviceData.getString("program_name");
        String programId = serviceData.getString("program_id");

        // Derive class name from program_id
        String className = programId + "Service";

        System.out.println("Generating: " + className + " from " + programName);

        // Create service class using Roaster
        JavaClassSource javaClass = Roaster.create(JavaClassSource.class);
        javaClass.setPackage(packageName + ".services");
        javaClass.setName(className);
        javaClass.setPublic();

        // Add imports
        javaClass.addImport("org.slf4j.Logger");
        javaClass.addImport("org.slf4j.LoggerFactory");
        javaClass.addImport("org.springframework.stereotype.Service");
        javaClass.addImport("org.springframework.transaction.annotation.Transactional");

        // Add @Service annotation
        javaClass.addAnnotation("Service");

        // Add JavaDoc
        javaClass.getJavaDoc().setText("Service class for " + programId + " operations.\nGenerated from COBOL program: " + programName + "\nGenerated by ServiceGeneratorV3 using Roaster.");

        // Add logger field
        FieldSource<JavaClassSource> loggerField = javaClass.addField();
        loggerField.setName("logger");
        loggerField.setType("Logger");
        loggerField.setPrivate();
        loggerField.setStatic(true);
        loggerField.setFinal(true);
        loggerField.setLiteralInitializer("LoggerFactory.getLogger(" + className + ".class)");

        // ENHANCEMENT 2025-10-26: Generate methods from paragraph_analysis
        // paragraph_analysis comes from Code Analysis V2 which extracts business logic from COBOL PROCEDURE DIVISION
        JSONArray paragraphAnalysis = serviceData.optJSONArray("paragraph_analysis");

        if (paragraphAnalysis != null && paragraphAnalysis.length() > 0) {
            System.out.println("  → Generating " + paragraphAnalysis.length() + " methods from paragraph analysis");

            // Generate a method for each paragraph
            for (int p = 0; p < paragraphAnalysis.length(); p++) {
                JSONObject paragraph = paragraphAnalysis.getJSONObject(p);
                generateMethodFromParagraph(javaClass, paragraph, programId, programName);
            }
        } else {
            // FALLBACK: No paragraph analysis available, generate empty execute() method (backward compatibility)
            System.out.println("  → No paragraph analysis found, generating stub execute() method");

            MethodSource<JavaClassSource> executeMethod = javaClass.addMethod();
            executeMethod.setName("execute");
            executeMethod.setPublic();
            executeMethod.setReturnType("void");
            executeMethod.addAnnotation("Transactional");

            String methodBody = String.format(
                "logger.info(\"Executing %s logic\");\n" +
                "// TODO: Implement business logic from %s\n" +
                "// This method was generated from COBOL program: %s\n" +
                "logger.info(\"%s execution completed\");",
                programId, programId, programName, programId
            );
            executeMethod.setBody(methodBody);
            executeMethod.getJavaDoc().setText("Execute main business logic from " + programId);
        }

        // Write to file
        Path outputPath = Paths.get(outputDir, packageName.replace('.', '/'), "services", className + ".java");
        Files.createDirectories(outputPath.getParent());

        Files.writeString(outputPath, javaClass.toString());

        System.out.println("  ✓ " + className + ".java created");

        // VALIDATE the generated code
        validateGeneratedCode(javaClass.toString(), className);
    }

    /**
     * ENHANCEMENT 2025-10-26: Generate a Java method from COBOL paragraph analysis
     *
     * Reads paragraph_analysis data from Code Analysis V2 which contains:
     * - name: COBOL paragraph name
     * - business_purpose: What the paragraph does
     * - java_method: { method_name, return_type, code }
     * - dependencies: Other paragraphs it calls
     * - criticality: Business importance
     */
    private static void generateMethodFromParagraph(JavaClassSource javaClass, JSONObject paragraph, String programId, String programName) {
        try {
            // Extract paragraph name and business purpose
            String paragraphName = paragraph.optString("name", "unknownParagraph");
            String businessPurpose = paragraph.optString("business_purpose", "Business logic from COBOL paragraph");

            // Extract java_method object (this contains the method signature and code)
            JSONObject javaMethodData = paragraph.optJSONObject("java_method");

            if (javaMethodData == null) {
                System.out.println("    → Skipping paragraph " + paragraphName + " (no java_method data)");
                return;
            }

            String methodName = javaMethodData.optString("method_name", "execute" + paragraphName.replaceAll("[^a-zA-Z0-9]", ""));
            String returnType = javaMethodData.optString("return_type", "void");
            String methodCode = javaMethodData.optString("code", "");

            System.out.println("    → Generating method: " + methodName + "() from paragraph " + paragraphName);

            // Create method using Roaster
            MethodSource<JavaClassSource> method = javaClass.addMethod();
            method.setName(methodName);
            method.setPublic();
            method.setReturnType(returnType);
            method.addAnnotation("Transactional");

            // Add Javadoc with business purpose and COBOL paragraph reference
            String javadoc = String.format(
                "%s\n\n" +
                "Original COBOL paragraph: %s\n" +
                "Program: %s",
                businessPurpose,
                paragraphName,
                programName
            );
            method.getJavaDoc().setText(javadoc);

            // Add method body
            if (methodCode != null && !methodCode.trim().isEmpty()) {
                // Use the AI-generated Java code from paragraph analysis
                method.setBody(methodCode);
            } else {
                // Fallback: Generate TODO placeholder
                String fallbackBody = String.format(
                    "logger.info(\"Executing %s from paragraph %s\");\n" +
                    "// TODO: %s\n" +
                    "// Original COBOL paragraph: %s\n" +
                    "logger.info(\"%s completed\");",
                    methodName, paragraphName, businessPurpose, paragraphName, methodName
                );
                method.setBody(fallbackBody);
            }

            System.out.println("      ✓ Method " + methodName + "() generated successfully");

        } catch (Exception e) {
            System.err.println("    ✗ ERROR generating method from paragraph: " + e.getMessage());
            e.printStackTrace();
            // Don't fail entire generation if one method fails - continue with others
        }
    }

    private static void validateGeneratedCode(String javaCode, String className) {
        System.out.println("  → Validating " + className + " with Roaster...");

        try {
            // Parse the generated code to validate syntax
            JavaClassSource parsed = Roaster.parse(JavaClassSource.class, javaCode);

            // Check for common issues
            if (parsed.getMethods().isEmpty()) {
                System.err.println("  ✗ WARNING: " + className + " has no methods");
            }

            if (!parsed.hasAnnotation("Service")) {
                System.err.println("  ✗ ERROR: " + className + " missing @Service annotation");
                throw new RuntimeException("Invalid service: missing @Service");
            }

            // Check for record with setters (V2 bug we're fixing!)
            if (parsed.toString().contains("record") && parsed.toString().contains("public void set")) {
                System.err.println("  ✗ ERROR: " + className + " has record with setters (immutability violation)");
                throw new RuntimeException("Invalid code: record cannot have setters");
            }

            System.out.println("  ✓ Validation passed for " + className);

        } catch (Exception e) {
            System.err.println("  ✗ VALIDATION FAILED: " + e.getMessage());
            throw new RuntimeException("Code validation failed for " + className, e);
        }
    }
}
