package com.modernized.testapp01;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * TestApp01 - Modernized Application
 * Generated by Java Generation V3
 *
 * This is a Modular Monolith organized by business domains.
 * Modernized from legacy COBOL application.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
